### PR TITLE
Support Node.js

### PR DESCRIPTION
**Pull request by iansu**
Fix for running in Node.js. Still need to update tests.

Test locally with this code:

```js
const thwack = require('thwack');
const fetch = require('node-fetch');

(async () => {
  const { data } = await thwack.get('http://donavon.com/', { fetch });

  console.log(data);
})();
```

### CODE REVIEW

**Comment by donavon** [comment]
Yeah, I was wondering how you were going to do that too 😁

Will something like this work?

https://jestjs.io/docs/en/configuration#testenvironment-string

**Comment by tomByrer** [comment]
Does it work in Dino?

**Comment by donavon** [comment]
@iansu That seems to do the trick. As I'm refactoring a bunch of tests, I'll take this over, if you don't mind.

**Comment by iansu** [comment]
Nice, I haven't seen that before. Happy to have you take over the tests.

**Comment by donavon** [comment]
Support was merged into `master` with f124b417b344c41b9c42ff7a7d54e3413f59ba37. It will be on npm when version `0.2.0` is published.

There is also support for node directly, without needing to `require('node-fetch')`.

```js
const thwack = require('thwack/node'); // for NodeJS 11+ or use "/node10" if on NodeJS 10

(async () => {
  const { data } = await thwack.get('http://donavon.com/', { fetch });

  console.log(data);
})();
```

**Comment by donavon** [comment]
Once again, thank you @iansu for kickstarting this!

**Pull request merged**
